steps:
    - name: node:12
      entrypoint: npm
      args: ['install']
    - name: node:12
      entrypoint: npm
      args: ['run', 'build']
      env:
          - 'NODE_ENV=production'
    - name: gcr.io/cloud-builders/gsutil # uploads the build files with Cloud Storage
      args: ['-m', 'rsync', '-r', '-c', '-d', './build', 'gs://gcp-remote/build']
    # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' # deploys server to App Engine
    #   entrypoint: 'bash'
    #   args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
    #   timeout: '1600s'
